from .orders.albom_controller import AlbomController
from .orders.country_controller import CountryController
from .orders.country_has_music_controller import CountryHasMusicController
from .orders.creator_controller import CreatorController
from .orders.creator_has_music_labels_controller import CreatorHasMusicLabelsController
from .orders.downloading_song_controller import DownloadingSongController
from .orders.downloading_song_has_person_profile_controller import DownloadingSongHasPersonProfileController
from .orders.follower_controller import FollowerController
from .orders.follower_has_creator_controller import FollowerHasCreatorController
from .orders.janre_controller import JanreController
from .orders.janre_has_music_controller import JanreHasMusicController
from .orders.music_controller import MusicController
from .orders.music_labels_controller import MusicLabelsController
from .orders.person_profile_controller import PersonProfileController

albom_controller = AlbomController()
country_controller = CountryController()
country_has_music_controller = CountryHasMusicController()
creator_controller = CreatorController()
creator_has_music_labels_controller = CreatorHasMusicLabelsController()
downloading_song_controller = DownloadingSongController()
downloading_song_has_person_profile_controller = DownloadingSongController()
follower_controller = FollowerController()
follower_has_creator_controller = FollowerHasCreatorController()
janre_controller = JanreController()
janre_has_music_controller = JanreHasMusicController()
music_controller = MusicController()
music_labels_controller = MusicLabelsController()
person_profile_controller = PersonProfileController()
